In [48]:
import pandas as pd
import numpy as np

In [49]:
labels = ['a','b','c']
list1 = [10,20,30]
a = np.array([10,20,30])
d= {'a':10,'b':20,'c':30}

In [50]:
pd.Series(data = list1)

0    10
1    20
2    30
dtype: int64

In [51]:
pd.Series(data = list1,index = labels)

a    10
b    20
c    30
dtype: int64

In [52]:
pd.Series(list1,labels)

a    10
b    20
c    30
dtype: int64

In [53]:
pd.Series(a)

0    10
1    20
2    30
dtype: int64

In [54]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [55]:
pd.Series(a,labels)

a    10
b    20
c    30
dtype: int64

In [56]:
ser1 = pd.Series([10,20,30,40], index =
['ferrari','lambo','bmw','benz'])
ser2 = pd.Series([10,30,40,50], index =
['ferrari','lambo','bmw','lexus'])
ser1 +ser2

benz        NaN
bmw        70.0
ferrari    20.0
lambo      50.0
lexus       NaN
dtype: float64

In [57]:
ser1["lambo"]

np.int64(20)

In [58]:
from numpy.random import randn
np.random.seed(101)
df = pd.DataFrame(randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split())
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [59]:
df['Z']

A    0.503826
B    0.605965
C   -0.589001
D    0.955057
E    0.683509
Name: Z, dtype: float64

In [60]:
df[['Z','X']]

          Z         X
A  0.503826  0.628133
B  0.605965 -0.319318
C -0.589001  0.740122
D  0.955057 -0.758872
E  0.683509  1.978757

In [61]:
df['new'] = df['Z'] + df['W']
df

          W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.210676
B  0.651118 -0.319318 -0.848077  0.605965  1.257083
C -2.018168  0.740122  0.528813 -0.589001 -2.607169
D  0.188695 -0.758872 -0.933237  0.955057  1.143752
E  0.190794  1.978757  2.605967  0.683509  0.874303

In [62]:
df.drop(columns ='new',axis=1)

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [63]:
df.drop(columns ='new')

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [64]:
df.drop(columns ='new',axis = 1,inplace=True)
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [65]:
df.loc['A']

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [66]:
df.iloc[2]

W   -2.018168
X    0.740122
Y    0.528813
Z   -0.589001
Name: C, dtype: float64

In [67]:
df.loc['A','Y']

np.float64(0.9079694464765431)

In [68]:
df.loc[['A','B'],['X','Y']]

          X         Y
A  0.628133  0.907969
B -0.319318 -0.848077

In [69]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [70]:
df>0

       W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [71]:
df[df>0]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [72]:
df[df['W']>0]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [73]:
df['W']>0

A     True
B     True
C    False
D     True
E     True
Name: W, dtype: bool

In [74]:
df[df['W']>0] ['Y']

A    0.907969
B   -0.848077
D   -0.933237
E    2.605967
Name: Y, dtype: float64

In [75]:
df[df['W']>0][['X','Y']]

          X         Y
A  0.628133  0.907969
B -0.319318 -0.848077
D -0.758872 -0.933237
E  1.978757  2.605967

In [76]:
df[(df['W']>0) & (df['Y']>1)]

          W         X         Y         Z
E  0.190794  1.978757  2.605967  0.683509

In [77]:
df = pd.DataFrame({'col1':[1,2,3,4],'col2':[44,55,66,44],'col3':
['abc','def','ghi','xyz']})
df.head()

   col1  col2 col3
0     1    44  abc
1     2    55  def
2     3    66  ghi
3     4    44  xyz

In [78]:
df['col2'].unique()

array([44, 55, 66])

In [79]:
df['col3'].nunique()

4

In [80]:
df['col3'].value_counts()

col3
abc    1
def    1
ghi    1
xyz    1
Name: count, dtype: int64

In [81]:
newdf= df[(df['col1']>2) & (df['col2']==44)]
newdf

   col1  col2 col3
3     4    44  xyz

In [82]:
def times2(x):
   return x*2
df['col1'].apply(times2)

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [83]:
df['col3'].apply(len)

0    3
1    3
2    3
3    3
Name: col3, dtype: int64

In [84]:
df['col1'].sum()

np.int64(10)

In [85]:
df

   col1  col2 col3
0     1    44  abc
1     2    55  def
2     3    66  ghi
3     4    44  xyz

In [86]:
del df['col1']
df

   col2 col3
0    44  abc
1    55  def
2    66  ghi
3    44  xyz

In [89]:
df.columns

Index(['col2', 'col3'], dtype='object')

In [90]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [91]:
df.sort_values(by='col2')

   col2 col3
0    44  abc
3    44  xyz
1    55  def
2    66  ghi

In [92]:
df.sort_values(by='col2', inplace = True)
df

   col2 col3
0    44  abc
3    44  xyz
1    55  def
2    66  ghi

In [93]:
df.isnull()

    col2   col3
0  False  False
3  False  False
1  False  False
2  False  False

In [108]:
df=pd.read_csv('/home/oem/Salaries(2).csv')
df

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148649,148650,Roy I Tillery,Custodian,0.00,0.00,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN
148650,148651,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148651,148652,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148652,148653,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.00,0.00,-618.13,0.0,-618.13,-618.13,2014,NaN,San Francisco,NaN

In [109]:
df.head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

In [110]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148654 non-null  int64
 1   EmployeeName      148654 non-null  object
 2   JobTitle          148654 non-null  object
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB

In [111]:
df['BasePay'].mean()

np.float64(66325.4488404877)

In [112]:
df['OvertimePay'].max()

np.float64(245131.88)

In [113]:
df[df['EmployeeName'] == 'JOSEPH DRISCOLL']['JobTitle' ]

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: object

In [114]:
df['TotalPayBenefits'] [df['EmployeeName']== 'JOSEPH DRISCOLL']

24    270324.91
Name: TotalPayBenefits, dtype: float64

In [115]:
df[df['TotalPay'].max()==df['TotalPay']]

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN

In [116]:
df[df['TotalPay'].min()==df['TotalPay']]

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.0,0.0,-618.13,0.0,-618.13,-618.13,2014,NaN,San Francisco,NaN

In [119]:
df.groupby('Year')['BasePay'].mean()

Year
2011    63595.956517
2012    65436.406857
2013    69630.030216
2014    66564.421924
Name: BasePay, dtype: float64

In [120]:
df['JobTitle'].nunique()

2159

In [121]:
df['JobTitle'].value_counts().head()

JobTitle
Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: count, dtype: int64

In [122]:
(df[df['Year']==2013]['JobTitle'].value_counts()==1).sum()

np.int64(202)

In [123]:
df['JobTitle'].apply(lambda str:('chief' in str.lower())).sum()

np.int64(627)

In [125]:
def find_chief(job_title):
    if 'chief' in job_title.lower().split():
        return True
    else:
        return False
df = pd.read_csv('Salaries(2).csv')
sum(df['JobTitle'].apply(lambda x: find_chief(x)))

477